### PR TITLE
feat: add modules from @nuxt-modules

### PR DESCRIPTION
**Pull request by Baroshem**
Hi team, I have recently released few useful modules for Nuxt 3 -> https://github.com/nuxt-modules

- https://github.com/nuxt-modules/algolia -> Easy integration with Algolia search using handy composables for search and indexing. In the upcoming weeks when guys from vue-instantsearch merge changes necessary for Nuxt 3 compatibility, there will be also a support for these components
- https://github.com/nuxt-modules/cache -> Browser & Server Cache module. Currently supporting only Browser with CacheControl headers, but working on support for cache-manager with redis, memcached, multi, etc that will be released in the upcoming days
- https://github.com/nuxt-modules/lazy-load -> Easy Lazy Loading images using Lozad.js. No configuration required apart from adding a simple class and modifying src to data-src and we have lazy loading images.
- https://github.com/nuxt-modules/compression -> Assets Compression module using vite-plugin-compression.

I have added them to the categories that I thought are the best but they can be changed accordingly :)

### CODE REVIEW

**Comment by Baroshem** [comment]
Hi Team

I have added another module (Compression) to this list. Also, I am not sure where to place Algolia module as it is currently in the Ecommerce section. Maybe it would be useful to have a section for `Search`? I can create this code if you think that will be useful (but I do not have an icon however).

Is there anything else I could do so that this PR would be ready to merge? :)

**Comment by pi0** [comment]
Hi @Baroshem. Thanks for the amazing new modules made for Nuxt3 ❤️  It would be nice if we can have a quick chat week before adding them to the modules listing.

**Comment by Baroshem** [comment]
Awesome @pi0, would you like to meet in Google Meet or chat via Discord? I am a member of Nuxt Discord. Jakub Andrzejewski#5753

**Comment by Baroshem** [comment]
@pi0 

I will close it for now as it is out of date. I will create separate pull requests for each module instead (starting with Algolia)

**Pull request closed without merging**
