### PR TITLE
design: filters component

### PR DESCRIPTION
**Pull request by r9mp**
@antfu This fixes what we said in the discord

- If I select a "Nuxt version" filter, I cannot unselect it.
- If I select a "Nuxt version" filter, then a "Catogories" filter, focus is lost in the "Nuxt version" filter, but filter stays in url.
- If I select a "Nuxt version" filter, then F5, the focus is lost.

I saw lots of other stuff... I'll write to you tomorrow.

Many more things could have been improved, but I need your agreement before (I would rework most of it... Which is possible :D)

### CODE REVIEW

**Comment by productdevbook** [comment]
change pr status drafk, buttons not working.


CleanShot 2021-11-18 at 09 32 39

**Comment by r9mp** [comment]
@productdevbook It's corrected! Sorry I applied prettier by mistake then rolled back to much XD

I tested again, it should be fine!

**Comment by productdevbook** [comment]
How to filter clear ?
CleanShot 2021-11-18 at 10 32 47@2x

**Comment by r9mp** [comment]
@productdevbook Done ; it was outside of the scope, so I just did no check for it.

Test it deeply. May still be bugs.

I'm not happy with my correction, for me everything should be a component et filters an array. If did stuff which are not "adaptable". But this is not to be made in this PR. I'll create a message about it on the discord channel.

**Pull request merged**
