### PR TITLE
feat: add `nuxt-icon-tw` (#799)

### PR DESCRIPTION
**Pull request by JohnCampionJr**

### CODE REVIEW

**Comment by Atinux** [comment]
Why not contributing to NuxtIcon instead?

**Comment by JohnCampionJr** [comment]
I can do that if you'd rather; I wasn't sure about adding the dependencies on Tailwind.  

That was my logic around that.

**Comment by JohnCampionJr** [comment]
For more context, this module assumes a Tailwind first preference.   It loads a modified version of @egoist Tailwind icon plugin that loads the found icon files and returns a list of them to this module.  This module adds Tailwind class names to the icons in <Icon> for those and reverts to standard Nuxt Icon loading for the rest.   

As such it felt like a breaking change which is why I put it as a separate module.

**Comment by JohnCampionJr** [comment]
@Atinux could I get this merged?

**Pull request merged**
