### PR TITLE
feat: add `nuxt-file-storage` module

### PR DESCRIPTION
**Pull request by NyllRE**
in reference to #926

### CODE REVIEW

**Comment by NyllRE** [comment]
hey @pi0 , are there any updates regarding the merge of this PR?

**Comment by pi0** [comment]
Hi dear @NyllRE sorry for late response on it. Your module sounds like a good idea reading from docs. 

Only i am concerned we might try to find a less confusing name both for package and exposed comosable. Made an issue for some suggestion: https://github.com/NyllRE/nuxt-nitro-storage/issues/2

**Comment by NyllRE** [comment]
I have closed https://github.com/NyllRE/nuxt-file-storage/issues/2 as I have successfully renamed everything requested. I hope everything is currently sufficient to add to the repository!

**Comment by pi0** [comment]
Thanks! Do you mind to update this PR to reflect renamings? 🙏🏼

**Review by pi0 — APPROVED** [review]
❤️

**Comment by NyllRE** [comment]
Thanks a lot for approving my Module! :heart:
I believe we just have to wait for ci to run in order for the merge to conclude?

**Pull request merged**
