### PR TITLE
Added named routes module

### PR DESCRIPTION
**Pull request by tiborpino**
Added named routes module

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @tiborpino 

I am not sure to fully understand the purpose of the module, could you give me an example of using it vs creating in `pages/` directory?

**Comment by tiborpino** [comment]
Hi @Atinux The main purpose is you can set custom key for every page inside pages directory and also custom url path for every route. Here is the example

I set named route key `custom-key` and custom url `/custom-url-for-homepage`  for /pages/homepage.vue

```
export default defineNuxtConfig({
  modules: [
    'nuxtjs-named-routes'
  ],
  namedRoutes: {
    routes: {
        'custom-key': {
            path: '/custom-url-for-homepage',
            file: '/pages/homepage.vue'
        }
    }
  }
}
```

Now I can use it as follows

```
<NuxtLink :to="{name: 'custom-key'}">Link to to homepage</NuxtLink>
```

And the generated html link will look like

```
<a href="/custom-url-for-homepage">Link to to homepage</a>
```

And now if I want to change file name to something like `/pages/index.vue` or just url for homepage `/new-url-for-homepage` my `<NuxtLink>` directive will be the same and I don't have to change anything inside my application.

**Comment by Atinux** [comment]
Indeed, I thought `definePageMeta` in the Vue page could actually do the trick, but it seems not: https://stackblitz.com/edit/github-n8wcq6?file=pages%2Fcustom-url-example.vue,pages%2Findex.vue

It would be nice to be able to leverage `definePageMeta` to update those meta informations. Would that be possible @pi0 @danielroe ?

**Comment by pi0** [comment]
It should be possible overriding name with pageMeta indeed. We already support similar `alias: '/custom'` with `definePageMeta` (https://stackblitz.com/edit/github-n8wcq6-p7fn2c?file=pages%2Fcustom-url-example.vue,pages%2Findex.vue)

**Comment by danielroe** [comment]
Agreed :+1:

**Comment by Atinux** [comment]
I guess this will land in RC13 👀

**Comment by danielroe** [comment]
~> https://github.com/nuxt/framework/pull/8633

**Comment by tiborpino** [comment]
> Indeed, I thought `definePageMeta` in the Vue page could actually do the trick, but it seems not: https://stackblitz.com/edit/github-n8wcq6?file=pages%2Fcustom-url-example.vue,pages%2Findex.vue
> 
> It would be nice to be able to leverage `definePageMeta` to update those meta informations. Would that be possible @pi0 @danielroe ?

No it won't. If you will define alias via page all your NuxtLink are fully dependent on the alias value. Change alias value and all links with that alias are broken.

My module will separate link key from file declaration and url for that page. When you decide to change page file name or page url, your key remains the same and all links are valid.

**Comment by Atinux** [comment]
By using Nuxt RC 13 (coming):

```ts
definePageMeta({
  name: 'my-key'
})
```

Will specify the name of the route, you can rename the page but the name won't change.

**Comment by tiborpino** [comment]
The code above will generate page on the url  /my-key

When you want to change the url, you have to change the key. Then all keys are invalid.

**Pull request closed without merging**
