### PR TITLE
feat: add nuxt-size

### PR DESCRIPTION
**Pull request by markthree**
https://github.com/markthree/nuxt-size

ultrafast get output size after build，power by [go-get-folder-size](https://github.com/markthree/go-get-folder-size)。

### CODE REVIEW

**Comment by Atinux** [comment]
Could you improve the readme to see the output please?

**Comment by markthree** [comment]
> Could you improve the readme to see the output please?

Added, and added gif snapshot 🥰

**Comment by Atinux** [comment]
I believe this should be part of Nitro or Nuxt directly instead of a module

**Comment by markthree** [comment]
Of course, it would be better

> I believe this should be part of Nitro or Nuxt directly instead of a module

**Comment by Atinux** [comment]
Do you mind opening an issue on Nitro and linking your module please @markthree 🙏

**Comment by markthree** [comment]
> Do you mind opening an issue on Nitro and linking your module please @markthree 🙏

of course 😁

**Pull request closed without merging**
