### PR TITLE
update xstate module

### LINKED ISSUE #465: Update `nuxt-xstate`
### Description

It would be neat to have a module updated with new info and maybe even a [picture of it's own](https://raw.githubusercontent.com/statelyai/public-assets/main/logos/xstate-logo-black-nobg.svg)

Recent update added nuxt bridge support

### Repository

https://github.com/Lexpeartha/nuxt-xstate

### npm

https://www.npmjs.com/package/nuxt-xstate

### Nuxt Compatibility

Nuxt Bridge, Nuxt 3

### PR DESCRIPTION
**Pull request by Lexpeartha**
Resolves #465

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Looks good to me. It's difficult to check locally if icon works, but I think it should probably be squarish.

**Comment by Lexpeartha** [comment]
image
Icon appears to be cut-off

**Comment by danielroe** [comment]
as I said... 😄  - it needs to be squarish.

**Comment by Lexpeartha** [comment]
To stop spamming PRs, here's "squarish" svg if you would like to commit directly:
```svg
<svg width="400px" height="400px" viewBox="0 0 400 400" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>XState</title>
    <g id="Logos" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="black" fill="#000000" transform="translate(120.000000, 120.000000)">
            <path d="M5.36289658,0.000339638022 L38.8274536,0.272242275 C42.0782395,0.298224393 45.1379106,1.81199651 47.1305054,4.38017671 L166.690531,158.436292 C169.400231,161.924484 166.911031,167 162.49858,167 L127.463572,167 C124.153622,167 121.032321,165.456769 119.02332,162.828377 L85.6788135,117.192826 L48.7744557,162.970452 C46.7597629,165.516033 43.6911801,167 40.444454,167 L5.31879657,167 C0.881845637,167 -1.59755488,161.877942 1.15379569,158.397098 L59.696558,84.2534136 L1.10234568,8.53465304 C-1.57795488,5.02441449 0.94799565,-0.0339543883 5.36534658,0.00278921133 L5.36289658,0.000339638022 Z M162.45448,0.000168973991 C166.913481,-0.0339543883 169.427181,5.10769999 166.66113,8.6032411 L114.42222,74.6094435 C110.695769,71.6773042 81.7784126,47.4681712 109.676569,15.0529676 C109.676569,15.0529676 111.859897,12.4994328 114.112032,9.85828289 L114.54822,9.34666074 L114.54822,9.34666074 L114.98272,8.83682365 C116.7128,6.80634291 118.320586,4.91405914 118.82487,4.30423994 C121.583571,0.965471521 123.854721,0.299187582 127.071572,0.274691849 L162.45448,0.000168973991 Z" id="x"/>
        </g>
    </g>
</svg>
```

**Pull request merged**
