### PR TITLE
Add nuxt-graphql-playground

### PR DESCRIPTION
**Pull request by tuarrep**
Add [`nuxt-graphql-playground`](https://github.com/pinpon-dev/nuxt-graphql-playground): A Nuxt.js module that injects a server route to serve [the GraphQL Playground](https://github.com/graphql/graphql-playground)

### CODE REVIEW

**Comment by Atinux** [comment]
Would love to have a review from @Diizzayy on this module 😊

**Comment by Diizzayy** [comment]
@Atinux Will do! I'll have a look

**Comment by Diizzayy** [comment]
@tuarrep I've made some slight improvements over at pinpon-dev/nuxt-graphql-playground#1

**Comment by tuarrep** [comment]
Thanks, I've merged this one.

Note to me : I need to better investigate virtuals… :)

**Pull request merged**
