### PR TITLE
feat: add nuxt-prometheus

### PR DESCRIPTION
**Pull request by artmizu**
I would like to propose my module that allows you to add Prometheus metrics to the Nuxt application

more info: [https://github.com/artmizu/nuxt-prometheus](https://github.com/artmizu/nuxt-prometheus)

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks @artmizu 

Isn't it better to name it `nuxt-prometheus` instead?

**Comment by artmizu** [comment]
@Atinux done. I have changed the name in the repository, npm and module description for consistency

**Comment by pi0** [comment]
Hi dear @artmizu. I have added some review notes in here: https://github.com/artmizu/nuxt-prometheus/issues/6

**Comment by artmizu** [comment]
@Atinux hi, i just added the features requested by @pi0 , so the module interface will not change in the near future. Can we merge this PR?

**Review by pi0 — APPROVED** [review]

**Pull request merged**
