### PR TITLE
feat: add `nuxt-posthog`

### PR DESCRIPTION
**Pull request by mitjans**

### CODE REVIEW

**Comment by Atinux** [comment]
Would be nice to have a real documentation before we can merge @mitjans

**Comment by mitjans** [comment]
Hi @Atinux! 

I've been able to set up some documentation for this module with Nuxt UI docs template to follow other modules' aesthetics. But then I saw that a Nuxt UI pro license is needed to deploy in production. I was wondering if it's possible to get a Nuxt UI pro license for the documentation of a community module.

If that's not the case (totally understandable), is there another docs template to use for community modules?

Thanks!

**Comment by Atinux** [comment]
Can you add to your nuxt.config.ts:

```ts
uiPro: { license: 'oss' }
```

I whitelisted your repo as it is open source and a Nuxt docs!

It would be nice to add a link back to Nuxt UI Pro as credit in the footer to help people discover it 😊

**Comment by mitjans** [comment]
Thanks @Atinux! 
I confirm that the deployment now works. I've also updated the documentation to include a footer link to Nuxt UI Pro.

**Pull request merged**
