### PR TITLE
feat: added nuxt-bootstrap-icons module

### PR DESCRIPTION
**Pull request by OyewoleOyedeji**
resolves https://github.com/nuxt/modules/issues/680

### CODE REVIEW

**Comment by OyewoleOyedeji** [comment]
PR for #680

**Review by danielroe — CHANGES_REQUESTED** [review]
would you remove the phosphor-icons svg from here?

**Comment by OyewoleOyedeji** [comment]
@danielroe I'm going to remove it

**Comment by OyewoleOyedeji** [comment]
Done

**Pull request merged**
