### PR TITLE
feat: website redesign

### PR DESCRIPTION
**Pull request by productdevbook**
TODO
- [x] Sidebar
- [ ] Mobile Design
- [x] New Card Design
- [x] Header add right svg design
- [x] Header title change
- [x]  Support dark mode
- [ ]  Fix windicss migration regressions
- [x]  Improve version compatibility badges design
- [ ]  Improve version switch design

New Design
CleanShot 2021-10-30 at 11 52 14@2x

Old Design
CleanShot 2021-10-30 at 11 46 17@2x

### CODE REVIEW

**Comment by Intevel** [comment]
I don't like those yellow and blue accents, otherwise this looks very good. Good job!

**Comment by owlnai** [comment]
We're currently discussing this redesign proposal [in a Discord thread](https://discord.com/channels/473401852243869706/473404156489498634/903929969460273172) in the Nuxt.js server 😄

**Comment by productdevbook** [comment]
New, coding ... with @owlnai 
CleanShot 2021-10-31 at 20 54 18

**Comment by antfu** [comment]
For anyone we just come by, here is the current design (awesome work @productdevbook @owlnai!)

image
image

**Review by antfu — APPROVED** [review]

**Comment by Intevel** [comment]
image

I think we should add margin on the sides

**Pull request merged**
