### PR TITLE
add pinia-nuxt-persist

### PR DESCRIPTION
**Pull request by 516310460**
client and server in pinia

### CODE REVIEW

**Comment by 516310460** [comment]
check

**Comment by 516310460** [comment]
link https://github.com/nuxt/modules/pull/397#issuecomment-1180310669

**Comment by Atinux** [comment]
Tested the playground on Stackblitz: https://stackblitz.com/github/516310460/pinia-nuxt-persist?file=playground%2Fapp.vue

The cookie persistence does not seem to work.

Also, I would like to have a review from Pinia's author @posva.

**Comment by posva** [comment]
I don't think it makes sense for pinia and `@pinia/nuxt` to be dependencies: https://github.com/516310460/pinia-nuxt-persist/blob/main/package.json#L35-L37 instead of peer deps
js-cookie is a dev dep but it's used in the plugin: https://github.com/516310460/pinia-nuxt-persist/blob/main/src/runtime/plugin.ts#L2

Other than that, I would say there are other pinia persist plugins out there with more downloads on npm. So maybe this should wait until the package has more users?

**Comment by 516310460** [comment]
> I don't think it makes sense for pinia and `@pinia/nuxt` to be dependencies: https://github.com/516310460/pinia-nuxt-persist/blob/main/package.json#L35-L37 instead of peer deps js-cookie is a dev dep but it's used in the plugin: https://github.com/516310460/pinia-nuxt-persist/blob/main/src/runtime/plugin.ts#L2
> 
> Other than that, I would say there are other pinia persist plugins out there with more downloads on npm. So maybe this should wait until the package has more users?

If both client and server are supported. I hope you can send me a link. This helps develop

**Pull request closed without merging**
