### PR TITLE
Fix #6

### LINKED ISSUE #6: Module Google-Analytics - Add support for google tag manager
Would be great having support for google tag manager since is a tool widely used for Marketing and being able to use the Data Layer.

### PR DESCRIPTION
**Pull request by DanielKulbe**
Add Google Tag Manager module

### CODE REVIEW

**Comment by pi0** [comment]
@DanielKulbe Thanks for contribution 🙌 I'll make some improvements on GA module soon so changes may be reflected to GTM to before module release. Also please don't commit `CHANGELOG` file as it is auto generated by lerna based on conventional commits.

**Comment by DanielKulbe** [comment]
OK, sure thing (good to know), I'll watch for changes and reflect accordingly, update the PR.

**Comment by pi0** [comment]
@DanielKulbe I've updated Google analytics module so it injects analytics script on page load. This helps giving faster and better reports.

**Comment by DanielKulbe** [comment]
👍 Improvements applied to the the new module ...

**Comment by pi0** [comment]
Seems nice +1. I will merge, assuming you already tested functionality ;)

**Pull request merged**
