### PR TITLE
Adds bulma module

### PR DESCRIPTION
**Pull request by rafamaciel**

### CODE REVIEW

**Comment by pi0** [comment]
Hi @rafamaciel Thanks for contribution 😍 Actually think we could ship vue components support too to this module like [bootstrap-vue](https://github.com/nuxt/modules/tree/master/modules/bootstrap-vue). (It can be then optionally enabled/disabled to just have css) . [buefy](https://github.com/rafaelpimpa/buefy) seems a good candidate. /cc  @rafaelpimpa

**Comment by rafaelpimpa** [comment]
Hey, anything I can help with?

**Comment by pi0** [comment]
Hey @rafaelpimpa, thanks for your time here.
Actually i love bluma and your work with buefy. However not sure about it's SSR support or any best practice for integration (with registering components or importing css). What is your opinion?

PS: modules are easy to use and reusable packages witch add various integrations such as buefy with just one or two lines of code and it is so important for us since it is going to be released as an official module :)

**Comment by rafaelpimpa** [comment]
I actually have never tested buefy on SSR but I heard some ppl were using it without any problems, I even got some PRs regarding it.

Right now I don't have the time to study about SSR and make a guide but I would love to help later on :)

**Comment by pi0** [comment]
Fine. So merging this for now. Please let us know when SSR was ready :)

**Pull request merged**
