### PR TITLE
Add firebase module

### PR DESCRIPTION
**Pull request by rafamaciel**
Add module to work with firebase

### CODE REVIEW

**Comment by pi0** [comment]
Hi @rafamaciel. This is awesome. Actually freebase is an important and useful module, So i will take extra care before release. Thanks

**Comment by rafamaciel** [comment]
Hi @pi0, what is the possibility of creating a new branch for this module? This would help a lot by moving from a slightly more complex module.

**Comment by pi0** [comment]
Actually i've done some local tests on your fork. Will merge for more work. MultiBranch + MonoRepo is something horrible ;)

**Comment by cappadona** [comment]
Thank you!
Spark by Readdle

**Comment by woodgates** [comment]
Hi @pi0, any news about this module? Vue is using Firebase DB in their examples and its amazing.

**Pull request merged**
