### PR TITLE
Add pinia-nuxt-persist and nuxt-swaggerjsonapi

### PR DESCRIPTION
**Pull request by 516310460**
Adds a new module [pinia-nuxt-persist](https://github.com/516310460/pinia-nuxt-persist).
Adds a new module [nuxt-swaggerjsonapi](https://github.com/516310460/nuxt-swaggerjsonapi).

### CODE REVIEW

**Comment by 516310460** [comment]
check

**Comment by Atinux** [comment]
Can you please open two prs please, one for each module

**Comment by 516310460** [comment]
okey

**Comment by 516310460** [comment]
link https://github.com/nuxt/modules/pull/397#issuecomment-1180310669

**Pull request closed without merging**
