### PR TITLE
Add nuxt-linkedin

### PR DESCRIPTION
**Pull request by devsourceid**
Repo : https://github.com/devsourceid/nuxt-linkedin
NPM : https://www.npmjs.com/package/nuxt-linkedin

### CODE REVIEW

**Comment by devsourceid** [comment]
> avoid

Okay i'll rename it, thankyou

**Review by claranceliberi — APPROVED** [review]

**Comment by pi0** [comment]
Improvements: https://github.com/devsourceid/nuxt-linkedin-insight-tag/issues/1

**Comment by pi0** [comment]
@devsourceid Sync script is failing since `npm` package in repo is wrong. Would you please fix it?

**Comment by pi0** [comment]
/reminder @devsourceid if you are still willing to maintain and include module

**Comment by pi0** [comment]
Closing due to inactivity.

**Pull request closed without merging**
