### PR TITLE
refactor: using script setup for CardModule

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Comment by pi0** [comment]
Can we please keep it in `CardModule` component? We soon need to simplify compat displaying so this might be unnecessary to separate a design that is only used inside card

**Comment by antfu** [comment]
My philosophy is trying to keep components simple to do their own job at once if possible. Giving that `index.vue` is quite huge to me, I was planning to break down things step by step (and also rewrite them to CAPI and script setup). I am aware that we might have new status - so I was trying to separate them out without touching the design so we could improve the displaying easier.

That said, I am totally fine with your decisions here, I was just thinking this might be a bit trivial to discuss opinions actually. Maybe we could settle an overall design philosophy that you would prefer so I can stick with it later on?

**Comment by pi0** [comment]
Splitting out `index.vue` is no brainer and amazing idea! Only for `CompactibiltyBadge` I was thinking it is too simple to be refactored out and considering future plans it will probably be even more simpler :)

**Review by pi0 — APPROVED** [review]

**Comment by antfu** [comment]
Sure. Done.

**Pull request merged**
