### PR TITLE
add nuxt-supabase

### PR DESCRIPTION
**Pull request by scottrobertson**

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
Thanks

**Comment by scottrobertson** [comment]
@pi0 what is the process for getting it added to `@nuxtjs/supabase` instead?

**Comment by pi0** [comment]
@scottrobertson For that we would need to move the module to [nuxt-community](https://github.com/nuxt-community/) but since you already have an official organization for supabase, I think it would be best keeping it as is or potentially using `@supabase/` namespace. 

By introducing module meta and kit, we probably open a system to add trusted badge to modules officially released by their vendor like this.

**Comment by scottrobertson** [comment]
@pi0 that makes total sense. Thank you.

**Pull request merged**
