### PR TITLE
💖 bring tailvue into the mix of 3rd party modules

### PR DESCRIPTION
**Pull request by acidjazz**

### CODE REVIEW

**Comment by Atinux** [comment]
Hey @acidjazz 

The logo should be a square actually

**Comment by acidjazz** [comment]
Hi @Atinux! You got it -  swapped for a square version.

**Comment by acidjazz** [comment]
much appreciated @Atinux  - just wondering - why doesnt it show up on nuxt.com/modules ?

**Comment by Atinux** [comment]
It is now: https://nuxt.com/modules/tailvue

**Pull request merged**
