### PR TITLE
feat: add nuxt-security module

### PR DESCRIPTION
**Pull request by Intevel**

### CODE REVIEW

**Comment by Baroshem** [comment]
Thanks for doing that! I really appreciate it! 💚

Let's merge it when it will be approved 😉

**Review by Baroshem — APPROVED** [review]

**Review by Atinux — APPROVED** [review]

**Comment by danielroe** [comment]
Added a couple of suggestions:
* https://github.com/Baroshem/nuxt-security/issues/27
* https://github.com/Baroshem/nuxt-security/issues/28

**Comment by pi0** [comment]
Hi @Intevel. Thanks for the nice efforts on security module 💯  I've made a quick review https://github.com/Baroshem/nuxt-security/issues/30 once solved i think we can list module 👍🏼

**Review by pi0 — APPROVED** [review]
Linked issues to be solved in next release

**Comment by Baroshem** [comment]
Thanks guys! 

I expect to release a new version tomorrow with all the recomendations :)

**Pull request merged**
