### PR TITLE
Add @eschricht/nuxt-color-mode module

### LINKED ISSUE #1064: [Module Listing Request]: `@eschricht/nuxt-color-mode`
### Description

A module similar to `@nuxtjs/color-mode` but with SSR support (through cookie and `sec-ch-prefers-color-scheme` header to fetch system preferred color scheme on server)

### Repository

https://github.com/Eschricht/nuxt-color-mode

### npm

https://www.npmjs.com/package/@eschricht/nuxt-color-mode

### Nuxt Compatibility

Nuxt 3

### PR DESCRIPTION
**Pull request by Eschricht**
### 🔗 Linked issue

resolves #1064

### ❓ Type of change

- [X] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Added `@eschricht/nuxt-color-mode` module

### CODE REVIEW

**Comment by atinux** [comment]
Thank you for working on this module, have you considered contributing to the main one?

`@nuxtjs/color-mode` support SSR **and** SSG actually (we don't need cookies to support this)

**Comment by atinux** [comment]
I just released the support for cookie storage!

Are you happy to help on `sec-ch-prefers-color-scheme` header detection?

**Comment by sharifzadesina** [comment]
@atinux Even with cookie storage it doesn't work with SSR. color mode updated only after app `mount` and interestingly, it is not reactive and usages like: `` doesn't work for whatever reason.

**Comment by atinux** [comment]
please open an issue there to discuss about it.

it is hard to handle all cases so there are specific reasons why it works this way. like how do you handle pre-rendering or cached pages?

**Comment by sharifzadesina** [comment]
@atinux I don't have any pre-render or caching if you mean that. by the way @Eschricht's module works without problem.

**Comment by atinux** [comment]
Yes but when you make a module you need to think of all use cases, this is why I had to make compromises.

BTW, how does it work for you `` if the preference is `system` and the server cannot detect the user color mode on the server?

**Comment by sharifzadesina** [comment]
@atinux I changed the preference from `system` to `light`, so we will always have a color mode before mounting.
The problem is that the module adds HTML class successfully before mount, but it is not able to detect a valid color mode before mount (even with cookie storage) and it causes a lot of problems.
It is supposed to detect user preferences in cookie storage.
I need to create a new issue with a demo for you.

**Pull request closed without merging**
