### PR TITLE
add nuxt-chiffre

### LINKED ISSUE #96: Add nuxt-chiffre
Repo: https://github.com/chiffre-io/nuxt-chiffre

Description: ~~Anonymous~~ Privacy first E2E encrypted analytics

### PR DESCRIPTION
**Pull request by tuarrep**
close #96

### CODE REVIEW

**Comment by franky47** [comment]
Could change the following fields please ?
```yml
description: 'Privacy-first, end-to-end encrypted analytics'
learn_more: 'https://chiffre.io'
category: Analytics # uppercase in other categories
maintainers:
  - name: Romain Clement
    github: rclement
    avatar: 'https://avatars.githubusercontent.com/u/1238873?v=4'
```

**Comment by tuarrep** [comment]
Done

@franky47 
All was mostly automatically generated from the GitHub repo. Perhaps you could update it to reflect this changes too.

**Review by franky47 — APPROVED** [review]

**Comment by Atinux** [comment]
Some notes regarding your repository:

- In the Readme, it says to use `modules: [['nuxt-chiffre']]`, it should be `modules: ['nuxt-chiffre']`
- There is not description on GH
Screenshot 2021-02-01 at 17 04 38

@pi0 do you have any other suggestions/requirements?

**Comment by franky47** [comment]
Repo description added and readme fixed, thanks for the heads-up !

**Review by Atinux — APPROVED** [review]

**Pull request merged**
