### PR TITLE
feat: add `nuxt-lazy-load`

### PR DESCRIPTION
**Pull request by darioferderber**

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks for the contribution, would you avoid naming it `nuxt3-` so it could work for Nuxt 4 and more?

Also, I am not sure to understand exactly what the module does, do you mind having a demo on Stackblitz for example?

**Comment by darioferderber** [comment]
Hi @Atinux 
I've created a [demo](https://stackblitz.com/edit/nuxt-starter-75qevf?file=package.json), but there are some problems 🙈 
It works perfectly fine on 3.3.2 (demo version) and older versions, but when I tried it with 3.3.3 it stopped working.

I'm adding **v-lazy-load** directive to the media files with **vite-plugin-replace** (basically replacing the element tag name with the tag name + v-lazy-load) - you can check it [here](https://gitlab.com/broj42/nuxt3-lazy-load/-/blob/main/src/module.js#L9).
```text.replace(regex, `<${tag} v-lazy-load `)```

Now it doesn't recognize directive on the client side, here is a [demo ](https://stackblitz.com/edit/nuxt-starter-jehvky?file=package.json)version with the 3.3.3. I can maybe find a workaround but I'm not sure if this is a bug with 3.3.3 version because the same principle worked in older versions, even in the Nuxt 2.

Cheers!

**Comment by darioferderber** [comment]
@Atinux I've found the issue, it's linked to this [issue](https://github.com/nuxt/nuxt/issues/20132).

I've fixed my Vite plugin to work with the versions > 3.3.2. and changed the name of the module to nuxt-lazy-load as you've requested

**Comment by darioferderber** [comment]
@danielroe I've added an icon and changed the compatibility to both Nuxt 2 and Nuxt 3.
Thanks!

**Review by danielroe — APPROVED** [review]

**Pull request merged**
