### PR TITLE
fix: add `nuxt-mongoose` icon

### PR DESCRIPTION
**Pull request by arashsheyda**

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
I think this might work better if it were square

**Comment by arashsheyda** [comment]
@danielroe ah yes, I tried to do so, but wasn't sure about it
there is this one, if you think it's better then it can be it or if you have any other idea
thanks

rocket

**Comment by danielroe** [comment]
That looks like it might be better, yes.

**Comment by Atinux** [comment]
Cannot we just add the Mongo icon?

**Comment by arashsheyda** [comment]
@Atinux yes sure

**Pull request merged**
