### PR TITLE
fix: focus/hover states for a11y

### PR DESCRIPTION
**Pull request by azrikahar**
I've noticed some buttons/links have `focus:outline-none` class which removes the focus border, but there isn't other mechanism used to replace it, so this PR aims to fix that. Here are some gifs to illustrate the issues & proposed fixes:

### Scenario 1

| | GIF |
|---|---|
| Before | QX8DdoMv7C |
| After | S0Tc6Es99k |

The above 2 gifs are timed roughly the same, and I was actually tabbing continuously in the "before" gif, but we can't see any indication of the focus states for the button and categories. The search input focus state is also abit too subtle, hence the usage of `shadow-outline-green` in my proposed fix which does exist to serve as a replacement when we use `focus:outline-none`, and is even recommended as seen in the tailwind docs: https://tailwindcss.com/docs/outline#usage

### Scenario 2

| | GIF |
|---|---|
| Before | xwjSBPaJpy |
| After | LPSrxOA8mN |

This is more of a design fix perhaps? I'm not sure where I've seen/heard this, but when we make the shadow larger, it can be better to actually "lift" up the object as well, since that is what we actually see in the real world. We can observe that lifted object's shadow will be larger/blurry compared to when it's on the ground, hence this interaction may feel more natural.

### Scenario 3

| | GIF |
|---|---|
| Before | dW96pCTzQ0 |
| After | oaAPyDjIQJ |

This is also a pretty subtle change for hover states of the links in each card. The focus outline are not removed in the cards, so I didn't implement any focus state changes here.

### CODE REVIEW

**Comment by pi0** [comment]
Hi @azrikahar This seems pretty cool 👌🤩 Do you mind fixing merge conflicts?

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Awesome work @azrikahar 

Do you mind resolving the conflicts so I can merge? :)

**Comment by azrikahar** [comment]
@pi0 @Atinux Thank you both for the kind words :) I've resolved the conflict, but apologies on the extra commits since I double backed and noticed the npm icon image size was resolved wrongly. 

For some reason the conflicted chunk of code wasn't the latest even when I've just recently forked this and created a branch from master. That's odd 🤔

**Comment by Atinux** [comment]
No worries since we do a squash and merge :)

**Pull request merged**
