### PR TITLE
feat: use unocss icons

### PR DESCRIPTION
**Pull request by antfu**
https://github.com/antfu/unocss/tree/main/packages/preset-icons

This allows us to have all the icons available to use without the need to create components for each every time.

### CODE REVIEW

**Comment by pi0** [comment]
(Adding pending label to validate `@nuxtjs/unocss` and potentially enable webpack support)

**Comment by productdevbook** [comment]
Wow, this is absolutely great.

**Comment by antfu** [comment]
Progress: https://github.com/antfu/unocss/pull/106

**Comment by antfu** [comment]
It's ready. Tested it on webpack mode and it works. Will send a PR to add UnoCSS to the modules list later :)

**Pull request merged**
